name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Python Backend ---
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest ici pour éviter une étape séparée

      - name: Create dummy test data
        run: |
          mkdir -p data/processed
          echo "date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country" > data/processed/train.csv
          echo "2010-01-01,300000.0,3.0,1.5,1500,5000,1.0,0,0,3,1200,300,1990,0,Main St,Seattle,WA 98101,USA" >> data/processed/train.csv
          cp data/processed/train.csv data/processed/test.csv

      - name: Run Python tests
        run: pytest

      - name: Build API Docker Image
        run: docker build -t house-price-api -f api/Dockerfile .

      # --- Node.js Frontend ---
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        env:
          CI: true

      # --- Deployment (Placeholders) ---
      - name: Notify staging deployment
        if: github.ref == 'refs/heads/develop'
        run: echo "Staging deployment would happen here"

      - name: Notify production deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Production deployment would happen here"